### PR TITLE
Upgrade prettier

### PR DESCRIPTION
**Pull request by relekang**

### CODE REVIEW

**Review by nierob — APPROVED** [review]
Looks good to me, thanks!
Btw the commit still has "fix" prefix, you may want to update it too.

**Comment by relekang** [comment]
It was intentional to have it in the commit.

**Comment by nierob** [comment]
> It was intentional to have it in the commit.

Why? The content of the commit shows that it was just an ordinary update. Unless through the update you tried to fix some issue, then I would be worth to mention what it was :-)

**Comment by relekang** [comment]
Because the [release process](https://github.com/DNBbank/eslint-config-dnb-open-banking/blob/master/package.json#L12) requires [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/)

**Pull request merged**
